# Generated by Django 5.0.4 on 2024-05-11 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_story_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='lang',
            field=models.CharField(default='english'),
        ),
    ]
