# Generated by Django 5.0.6 on 2024-05-20 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_story_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='isPublic',
            field=models.BooleanField(default=True),
        ),
    ]
